# Generated by Django 4.0 on 2022-01-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_table_number'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'pagos'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(choices=[('CARD', 'card'), ('CASH', 'cash')], max_length=255, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statusPayment',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid')], max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='totalPayment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe total'),
        ),
    ]
