# Generated by Django 4.0 on 2022-01-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
    ]
